on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Set Up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 

      - name: Display Python Version
        run: python -c "import sys; print(sys.version)"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
      
      - name: Create Executable
        run: pyinstaller --onefile src/script.py

      - name: Publish a New Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: dist/script.exe
          token: ${{ secrets.GITHUB_TOKEN }}